version: '3.9'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestkit
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nestkit.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'

  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    container_name: nestkit-api
    ports:
      - '3000:3000'
    depends_on:
      - db
    secrets:
      - JWT_SECRET
      - JWT_REFRESH_SECRET
      - JWT_EXPIRES_IN
      - JWT_REFRESH_EXPIRES_IN
      - DATABASE_URL
      - PORT

secrets:
  JWT_SECRET:
    file: ./secrets/JWT_SECRET
  JWT_REFRESH_SECRET:
    file: ./secrets/JWT_REFRESH_SECRET
  JWT_EXPIRES_IN:
    file: ./secrets/JWT_EXPIRES_IN
  JWT_REFRESH_EXPIRES_IN:
    file: ./secrets/JWT_REFRESH_EXPIRES_IN
  DATABASE_URL:
    file: ./secrets/DATABASE_URL
  PORT:
    file: ./secrets/PORT

volumes:
  postgres_data:
