name: Publish Swagger Docs

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Generate Swagger docs
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/nestkit
          JWT_SECRET: test_jwt_secret
          JWT_REFRESH_SECRET: test_refresh_secret
          JWT_EXPIRES_IN: 3600s
          JWT_REFRESH_EXPIRES_IN: 7d
          PORT: 3000
        run: npm run generate:docs

      - name: Copy Swagger UI
        run: |
          mkdir -p docs
          cp -r node_modules/swagger-ui-dist/* docs
          cp docs/swagger.json docs/swagger-initializer.json
          echo "window.onload = function() {
            window.ui = SwaggerUIBundle({
              url: 'swagger.json',
              dom_id: '#swagger-ui',
              presets: [
                SwaggerUIBundle.presets.apis,
                SwaggerUIStandalonePreset
              ],
              layout: 'BaseLayout',
              deepLinking: true
            });
          };" > docs/swagger-initializer.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
